version: '3'

services:
  db:
    container_name: db
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    restart: always
  dbadmin:
    container_name: dbadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db:db
    restart: always
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    restart: always
  web00:
    container_name: web00
    image: richarvey/nginx-php-fpm:1.10.1
    depends_on:
      - "db"
    volumes:
      - ./erp/dolibarr00/htdocs:/var/www/html
    restart: always
  web01:
    container_name: web01
    image: richarvey/nginx-php-fpm:1.10.1
    depends_on:
      - "db"
    volumes:
      - ./erp/dolibarr01/htdocs:/var/www/html
    restart: always
  web02:
    container_name: web02
    image: richarvey/nginx-php-fpm:1.10.1
    depends_on:
      - "db"
    volumes:
      - ./erp/dolibarr02/htdocs:/var/www/html
    restart: always
  web03:
    container_name: web03
    image: richarvey/nginx-php-fpm:1.10.1
    depends_on:
      - "db"
    volumes:
      - ./erp/dolibarr03/htdocs:/var/www/html
    restart: always
